name = "Reproduce"
uuid = "560a9c3a-0b8c-11e9-0329-d39dfcb85ed2"
authors = ["Matt <mkschleg@gmail.com>"]
version = "0.13.1-dev"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CodeTracking = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MySQL = "39abe10b-433b-5dbd-92d4-e302a9df00cd"
Parallelism = "c8c83da1-e5f9-4e2c-a857-b8617bac3554"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
BSON = "0.2, 0.3"
CodeTracking = "0.5, 1"
DBInterface = "2"
DataFrames = "1"
FileIO = "1"
Git = "0.3, 1"
HDF5 = "0.12, 0.13, 0.14, 0.15, 0.16"
JLD2 = "0.1, 0.2, 0.3, 0.4"
JSON = "0.20, 0.21"
MacroTools = "0.5"
MySQL = "1"
Parallelism = "0.1"
ProgressMeter = "1"
Reexport = "1"
TOML = "1.0"
Tables = "1"
julia = "^1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
